
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 触发条件，推送到 main 分支时执行
  pull_request:
    branches:
      - main  # 触发条件，提交到 main 分支时执行

jobs:
  deploy:
    runs-on: ubuntu-22.04  # 设置运行环境
    permissions:
      contents: write  # 允许写入内容
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}  # 避免并发运行

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true  # 如果有子模块需要拉取
          fetch-depth: 0    # 拉取完整历史，以便于获取完整信息（如 .GitInfo）

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # 设置 Python 版本，可以根据需要调整

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install blogx==0.3.0  # 安装 blogx

      - name: Build the blog
        run: |
          blogx build  # 运行 blogx 构建静态文件

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'  # 仅在 main 分支执行
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token
          publish_dir: ./dist  # 指向生成的静态文件目录
