
name: Upload to local server

on:
  workflow_run:
    workflows: ["Deploy to GitHub Pages"]  # 监听 deploy.yml
    types:
      - completed  # 仅在工作流完成时触发

jobs:
    upload:
        runs-on: ubuntu-22.04  # 设置运行环境
        permissions:
            contents: write  # 允许写入内容
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}  # 避免并发运行

        if: ${{ github.event.workflow_run.conclusion == 'success' && vars.UPLOAD_ENABLED == 'true' }}  # 添加条件

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                ref: gh-pages

            - name: Install rsync and sshpass
              run: sudo apt-get install rsync sshpass -y

            - name: show current directory
              run: pwd && ls -al

            - name: Upload files
              run: |
                rsync -avz --delete -e "sshpass -p '${{ secrets.SERVER_SSH_PASSWORD }}' ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.SERVER_WWWROOT_DIR }}
